set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'mileszs/ack.vim'
Plug 'majutsushi/tagbar'
Plug 'morhetz/gruvbox'
Plug 'scrooloose/nerdcommenter'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'airblade/vim-gitgutter'
call plug#end()


set showmode
set nowrap
set textwidth=120
set tags=tags
set softtabstop=4
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set shiftround
set backspace=indent,eol,start
set autoindent
set copyindent
set number
set ignorecase
set relativenumber
set cc=80

set hlsearch
set laststatus=2  
set ruler 
set incsearch

map <C-n> : NERDTreeToggle<CR>
nmap <F8> : TagbarToggle<CR>

syntax on
set termguicolors
colorscheme gruvbox
set background=dark


set encoding=utf-8
